config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root 'home#index'
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  resources :organisations do
    resources :articles do
      resources :attachments
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  versioned

  belongs_to :user
  belongs_to :organisation
  has_many :attachments, dependent: :destroy
  has_many :attachment_trackers, dependent: :destroy

  accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: proc { |a| a[:image].blank? }

  validates_presence_of :user_id, :organisation_id, :title, :body
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  versioned

  belongs_to :article

  has_attached_file :image,
                    :keep_old_files => true,
                    :styles => { :medium => "400x400#",:thumb => "100x100#" },
                    :url => "/attachments/articles/:article_id/:id/version_:version/:style/:basename.:extension",
                    :path => ":rails_root/public/attachments/articles/:article_id/:id/version_:version/:style/:basename.:extension"

  validates_attachment 	:image,
                        :presence => true,
                        :content_type => { :content_type => /\Aimage\/.*\Z/ },
                        :size => { :less_than => 2.megabytes }

  Paperclip.interpolates :article_id do |attachment, style|
    attachment.instance.article_id.to_s
  end

  Paperclip.interpolates :version do |attachment, style|
    attachment.instance.version.to_s
  end

  Paperclip.registered_attachments_styles_path = "#{Rails.root}/public/attachments/paperclip_attachments.yml"
end

app/models/attachment_tracker.rb
class AttachmentTracker < ActiveRecord::Base
  belongs_to :article

  validates_presence_of :version_id, :attachments
end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
  has_many :users
  has_many :articles
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :organisation
  has_many :articles, through: :organisation
  before_save :assign_organisation

  validates_presence_of :name


  private

  def assign_organisation
    self.organisation_id = Organisation.all.map(&:id).sample
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :set_article, except: [:new, :create]

  def new
    @organisation = Organisation.find(params[:organisation_id])
    @article = Article.new
    2.times do
      @article.attachments.build
    end
  end

  def create
    @organisation = Organisation.find(params[:organisation_id])
    @article = @organisation.articles.build(article_params)
    @article.user_id = current_user.id
    if @article.save
      create_attachments_tracker(@article, @article.attachments.map(&:id))
      redirect_to organisation_article_path(@organisation,@article), :notice => "Successfully created article"
    else
      render 'new'
    end
  end

  def show
    @article.revert_to(params[:version].to_i) if params[:version]
    @attachments = @article.attachments.find(article_version)
  end

  def edit
  end

  def update
    if @article.update_attributes(article_params)
      create_attachments_tracker(@article, params[:preserved_attachments])
      redirect_to organisation_article_path(@organisation,@article), :notice => "Successfully updated article"
    else
      render 'edit'
    end
  end


  private

  def create_attachments_tracker(article, attachment_ids)
    tracker =  @article.attachment_trackers.find_by version_id: article.version
    if tracker.nil?
      article.attachment_trackers.create(version_id: article.version, attachments: attachment_ids)
    else
     tracker.update_attribute(:attachments, attachment_ids)
    end
  end

  def set_article
    @organisation = Organisation.find(params[:organisation_id])
    @article = @organisation.articles.find(params[:id])
  end

  def article_version
    @article.attachment_trackers.find_by(version_id: @article.version).attachments.map{|x| x.to_i }
  end

  def article_params
    params.require(:article).permit(:title, :body, attachments_attributes: [:image,:_destroy, :id])
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  def show
    @organisation = Organisation.find(params[:organisation_id])
    @article = @organisation.articles.find(params[:article_id])
    @attachment = @article.attachments.find(params[:id])
    @attachment.revert_to(params[:version].to_i) if params[:version]
  end

  def edit
    @organisation = Organisation.find(params[:organisation_id])
    @article = @organisation.articles.find(params[:article_id])
    @attachment = @article.attachments.find(params[:id])
  end

  def update
    @organisation = Organisation.find(params[:organisation_id])
    @article = @organisation.articles.find(params[:article_id])
    @attachment = @article.attachments.find(params[:id])
    if @attachment.update_attributes(attachment_params)
      redirect_to [@organisation,@article,@attachement]
    else
      render 'edit'
    end
  end

  private

  def attachment_params
    params.require(:attachment).permit(:image)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  def index
    @organisations = Organisation.all
  end

  def new
    @organisation = Organisation.new
  end

  def create
    @organisation = Organisation.create(organisation_params)
    if @organisation.save
      redirect_to organisations_path, :notice => "Organisation was successfully created"
    else
      render 'new'
    end
  end

  def show
    @organisation = Organisation.find(params[:id])
  end

  private

  def organisation_params
    params.require(:organisation).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
      when :notice then "alert alert-success"
      when :info then "alert alert-info"
      when :alert then "alert alert-danger"
      when :warning then "alert alert-warning"
    end
  end

  def errors_for(resource)
    if resource.errors.any?
      content_tag :div,:class => 'alert alert-danger', :role => 'alert' do
        resource.errors.full_messages.collect do |msg|
          content_tag :p, msg
        end
      end.html_safe
    end
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end

  private

  def link_to_function(name, function, html_options={})
    onclick = "#{"#{html_options[:onclick]}; " if html_options[:onclick]}#{function}; return false;"
    href = html_options[:href] || '#'

    content_tag(:a, name, html_options.merge(:href => href, :onclick => onclick))
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/views/articles/_article.html.erb
<h4><%= link_to article.title, [@organisation, article] %></h4>
<p><%= truncate article.body, length: 300 %></p>

app/views/articles/_attachment_fields.html.erb
<div class="form-group">
  <label for="file">File input</label>
  <%= f.file_field :image %>
  <p class="help-block"> <%= link_to_function "Remove", "remove_fields(this)" %></p>
</div>

app/views/articles/_form.html.erb
<div class="col-md-12">

  <% if @article.errors.any? %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <strong>Ooops!</strong> something's not right
        <% @article.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
        <% end %>
      </div>
  <% end %>


  <%= form_for([@organisation, @article], html: { multipart: true, role: "form" }) do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
      </div>

      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control", rows: 7, cols: 30 %>
      </div>

      <div class="form-group">
        <%= f.fields_for :attachments do |builder| %>
            <% if builder.object.new_record? %>
                <%= render 'attachment_fields', :f => builder %>
            <% else %>
                <div class="col-md-2">
                  <%= link_to image_tag(builder.object.image.url(:medium)), [@organisation, @article, builder.object], class: "thumbnail" %>
                  <div class="checkbox">
                    <label>
                      <%= check_box_tag "preserved_attachments[]", builder.object.id %> Keep
                    </label>
                  </div>
                </div>
            <% end %>
        <% end %>
      </div>

      <div class="form-group">
        <%= link_to_add_fields "Add Attachment", f, :attachments if @article.new_record? %>
      </div>

      <div class="form-group" style="clear: both; margin-top: 20px">
        <%= f.submit class: "btn btn-danger btn-lg" %>
      </div>


  <% end %>
</div>

app/views/articles/edit.html.erb
<div class="col-md-12 margin-top-50">
  <%= link_to "Back to article", organisation_article_path(@organisation, @article), class: "btn btn-warning" %><br><br>
  <%= render 'form' %>
</div>

app/views/articles/new.html.erb
<div class="col-md-12 margin-top-50">
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="col-md-12">
  <h2><%= @article.title %></h2>

  <p><%= @article.body %></p>

  <h4>
    <%= link_to "Edit", edit_organisation_article_path(@organisation, @article) %>
    | Version <%= @article.version %> of <%= @article.versions.count + 1 %>
    <% if @article.version > 1 %>
        | <%= link_to "Previous version", organisation_article_path(:version => @article.version-1)%>
    <% end %>
    <% if params[:version] %>
        | <%= link_to "Latest version", organisation_article_path %>
    <% end %>
  </h4>
</div>


<div class="col-md-12">
  <h3>Attachments</h3>
</div>

<% if @attachments.any? %>
    <%= render @attachments %>
<% else %>
    <div class="col-md-12">
      <p>No attachement</p>
    </div>
<% end %>

app/views/attachments/_attachment.html.erb
<div class="col-md-2">
  <%= link_to image_tag(attachment.image.url(:medium)), [@organisation,@article, attachment], class: "thumbnail" %>
</div>

app/views/attachments/edit.html.erb
<div class="col-md-12">
  <h2>Edit Attachment</h2>
  <%= image_tag @attachment.image.url(:medium), class: "thumbnail" %>
  <%= form_for([@organisation,@article,@attachment], html: { multipart: true }) do |f| %>
      <div class="form-group">
        <label for="file">File input</label>
        <%= f.file_field :image %>
        <p class="help-block">Upload image file</p>
      </div>

      <div class="form-group">
        <%= f.submit "Update Attachment", class: "btn btn-danger" %>
      </div>
  <% end %>
</div>

app/views/attachments/show.html.erb
<div class="col-md-4 col-md-offset-4 thumbnail">
  <%= link_to image_tag(@attachment.image.url(:medium)), @attachment.image.url %>
  <div class="caption">
    <h3>Version <%= @attachment.version %> of <%= @attachment.versions.count + 1 %></h3>

    <div class="button-group">
      <%= link_to "Edit", edit_organisation_article_attachment_path(@organisation, @article, @attachment), class: "btn btn-primary " %>
      <% if @attachment.version > 1 %>
          <%= link_to "Prev version", [@organisation, @article, @attachment, version: @attachment.version-1],  class: "btn btn-info"  %>
      <% end %>
      <% if params[:version] %>
          <%= link_to "Latest version", organisation_article_attachment_path,  class: "btn btn-danger"  %>
      <% end %>

    </div>


    <br><br>
    <%= link_to "Back to article", organisation_article_path(@organisation, @article), class: "btn btn-warning col-md-12" %>

  </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron text-center">
  <h1>Hello <%= current_user.name %></h1>
  <% if current_user.organisation.present? %>
    <p>  <%= link_to "New Article", new_organisation_article_path(current_user.organisation), class: "btn btn-success btn-lg" %>  </p>
  <% end %>
</div>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Versioner</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= render 'layouts/shim' %>
</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Versioner", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= controller_name == "home" ? "active" : "" %>"><%= link_to "Home", root_path %></li>
        <li class="<%= controller_name == "organisations" ? "active" : "" %>"><%= link_to "Organisations", organisations_path %></li>
        <% if user_signed_in? %>
          <li class="pull-right"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li class="pull-right"><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
        <li class="pull-right">
        <% if user_signed_in? %>
            <% if current_user.organisation.present? %>
              <form class="pull-right">
                <%= link_to "New Article", new_organisation_article_path(current_user.organisation), class: "btn navbar-btn btn-danger" %>
              </form>
            <% end %>
        <% end %>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<div class="container">

  <div class="row">
    <div class="col-md-12">
      <% flash.each do |key, value| %>
          <div class="text-center alert-dismissible  <%= flash_class(key) %>" role="alert">
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
            </button>
            <%= value %>
          </div>
      <% end %>
    </div>
    </div>

    <div class="row">
      <%= yield %>
    </div>
  </div>
</div><!-- /.container -->
</body>
</html>

app/views/organisations/_organisation.html.erb
<%= link_to organisation.name, organisation, class: "list-group-item" %>

app/views/organisations/index.html.erb
<div class="jumbotron text-center">
  <h1>Organisations!</h1>
  <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet.</p>
  <p><%= link_to "Create Organisation", new_organisation_path, class: "btn btn-lg btn-success", role: "button" %></p>
</div>

<div class="col-md-12">
  <% if @organisations.any? %>
      <div class="list-group">
        <%= render @organisations %>
      </div>
  <% end %>
</div>

app/views/organisations/new.html.erb
<div class="col-md-12 margin-top-50">
  <%= errors_for @organisation %>
  <%= form_for @organisation do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

      <%= f.submit "Create" %>
  <% end %>
</div>

app/views/organisations/show.html.erb
<div class="jumbotron">
  <h1><%= @organisation.name %></h1>
  <p class="lead"><%= @organisation.description %></p>
</div>
<div class="col-md-12">
  <h2>Articles</h2>
  <% if @organisation.articles.any? %>
      <%= render @organisation.articles %>
  <% else %>
      <p>No articles found for this organisation</p>
  <% end %>
</div>